<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>shen</string>
	</array>
	<key>name</key>
	<string>Shen</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#parens</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\\.*$</string>
					<key>name</key>
					<string>comment.line.documentation.source.shen</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\\\*</string>
					<key>end</key>
					<string>\*\\</string>
					<key>name</key>
					<string>comment.block.source.shen</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\s\(](and|or|if|lambda|freeze|let|cond|simple-error|trap-error|where|package|defun|/.|-&gt;|&lt;-|:=|define|defmacro|defcc|defprolog)[\s\)]</string>
					<key>name</key>
					<string>meta.keywords.source.shen</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\s\(][\-\+]*(0|([1-9][0-9_]*))[\s\(]</string>
					<key>name</key>
					<string>constant.numeric.integer.source.shen</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\s\(](true|false|\(\))[\s\)]</string>
					<key>name</key>
					<string>constant.language.source.shen</string>
				</dict>
			</array>
		</dict>
		<key>parens</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.begin.shen</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.end.shen</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.group.shen</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parens</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#squares</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>squares</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.begin.shen</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.end.shen</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.group.shen</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parens</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#squares</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^\\](\"[^\"]*\")</string>
					<key>name</key>
					<string>string.quoted.double.source.shen</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.shen</string>
	<key>uuid</key>
	<string>4f20d927-cddd-4fd7-a7a6-9739f008439d</string>
</dict>
</plist>
