<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>shen</string>
	</array>
	<key>name</key>
	<string>Shen</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.source.shen</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[^\\](\"[^\"]*\")</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.shen</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.source.shen</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\((define)\s+([a-zA-Z0-9_\-?\+^]+)\s*</string>
			<key>name</key>
			<string>meta.variable.source.shen</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.shen</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[\s\(](and|or|if|lambda|freeze|let|cond|simple-error|trap-error|where|package|defun|-&gt;|&lt;-|:=|define|defmacro|defcc|defprolog)[\s\)]</string>
			<key>name</key>
			<string>meta.keywords.source.shen</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.shen</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[\s\(](true|false|\(\))[\s\)]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.shen</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#\\[a-zA-Z0-9_\-?\+\.\!\"]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0|([1-9][0-9_]*))\b</string>
			<key>name</key>
			<string>constant.numeric.integer.source.shen</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\\\\</string>
			<key>end</key>
			<string>$\n</string>
			<key>name</key>
			<string>comment.line.documentation.source.shen</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\\\*</string>
			<key>end</key>
			<string>\*\\</string>
			<key>name</key>
			<string>comment.block.source.shen</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.shen</string>
	<key>uuid</key>
	<string>4f20d927-cddd-4fd7-a7a6-9739f008439d</string>
</dict>
</plist>